---

- name: enable the cluster
  uri:
    url:              "http://localhost:5984/_cluster_setup"
    body:             "{{ lookup('template','enable_cluster.json')}}"
    status_code:      201
    headers:
      Content-Type:   "application/json"
    user:             admin
    password:         "{{ admin_password }}"
    method:           POST
    body_format:      json
    force_basic_auth: yes
  register:      cluster_status
  ignore_errors: true  

- name: add nodes to the cluster - PART 1
  uri:
    url:              "http://localhost:5984/_cluster_setup"
    body:             "{{ lookup('template','add_node_part_1.json')}}"
    status_code:      201,409
    headers:
      Content-Type:   "application/json"
    user:             admin
    password:         "{{ admin_password }}"
    method:           POST
    body_format:      json
    force_basic_auth: yes
  with_items: "{{ groups['couchdb'] }}"
  when:
    - inventory_hostname == groups['couchdb'][0]
    - inventory_hostname != item

- name: add nodes to the cluster - PART 2
  uri:
    url:              "http://localhost:5984/_cluster_setup"
    body:             "{{ lookup('template','add_node_part_2.json')}}"
    status_code:      201,409
    headers:
      Content-Type:   "application/json"
    user:             admin
    password:         "{{ admin_password }}"
    method:           POST
    body_format:      json
    force_basic_auth: yes
  with_items: "{{ groups['couchdb'] }}"
  when:
    - inventory_hostname == groups['couchdb'][0]
    - inventory_hostname != item

- name: finish the cluster
  uri:
    url:              "http://localhost:5984/_cluster_setup"
    body:             '{"action":"finish_cluster"}'
    status_code:      201,400
    headers:
      Content-Type:   "application/json"
    user:             admin
    password:         "{{ admin_password }}"
    method:           POST
    body_format:      json
    force_basic_auth: yes
  when:
    - inventory_hostname == groups['couchdb'][0]
