---

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Add couchdb Apt signing key
  apt_key:
    url:    "http://couchdb.apache.org/repo/bintray-pubkey.asc"
    state:  present

- name: Add apt repo for couchdb
  apt_repository:
    repo:     "deb http://apache.bintray.com/couchdb-deb {{ ansible_distribution_release }} main"
    state:    present
    filename: couchdb

- name: Install Couchdb package
  apt:
    name:   "couchdb={{ couchdb_version }}~{{ ansible_distribution_release }}"
    state:  present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Stop couchdb service before changing config
  service:
    name:     couchdb
    state:    stopped
    enabled:  True

- name: Put the local.ini file on couchdb server
  template:
    src:    local.ini.j2
    dest:   "{{ couchdb_config_folder }}/local.d/custom.ini"
    owner:  "{{ couchdb_user }}"
    group:  "{{ couchdb_group }}"
    mode:   0755

- name: Put the vm.args file on couchdb server
  template:
    src:    vm.args.j2
    dest:   "{{ couchdb_config_folder }}/vm.args"
    owner:  "{{ couchdb_user }}"
    group:  "{{ couchdb_group }}"
    mode:   0755

- name: Start couchdb service and ensure it's running
  service:
    name:     couchdb
    state:    started
    enabled:  True

- name: wait for couchdb port to start listening
  wait_for:
    host:     127.0.0.1
    port:     5984
    timeout:  120

- name:    Configure couchdb cluster
  include: couchdb_cluster_setup.yml
  when:    (cluster_setup == True)  and ( hosts_count | int > 1 )
